---
- name: install apache and php packages
  apt:
    name:
      - "apache2"
      - "libapache2-mod-php"
      - "php{{ php_version }}-curl"
      - "php{{ php_version }}-gd"
      - "php{{ php_version }}-intl"
      - "php{{ php_version }}-mbstring"
      - "php{{ php_version }}-mysql"
      - "php{{ php_version }}-xml"
      - "php{{ php_version }}-zip"
    state: present
    update_cache: yes

- name: Start apache2
  service:
    name: apache2
    state: started
  notify:
    - restart apache2

- name: Copy virtual host configuration
  template:
    src: "virtual_host_conf.j2"
    dest: "/etc/apache2/sites-available/{{ server_hostname }}.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart apache2

- name: a2ensite {{ server_hostname }}.conf
  command: "a2ensite {{ server_hostname }}.conf"
  notify:
    - restart apache2 
