---

- name: Add php repository
  tags: php
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Install php extensions
  tags: php
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php{{ php_version }}
    - php{{ php_version }}-mysql
    - php{{ php_version }}-gd
    - php-ssh2
    - php{{ php_version }}-mcrypt 
    - php{{ php_version }}-fpm 

- name: Setup php-fpm
  tags: php
  replace: dest=/etc/php/{{ php_version }}/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart php-fpm


- name: Create pool
  tags: php
  template: 
    src: "pool.conf.j2"
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/{{ server_hostname }}.conf"
    owner: www-data 
    group: www-data
    mode: 0644
  notify:
    - restart php-fpm

- name: Crate /var/log/php-fpm
  tags: php
  file:
    state: directory
    path: "/var/log/php-fpm/"
    owner: www-data
    group: www-data
    mode: 0755

- name: Ensure error log file exists
  tags: php
  copy:
    content: ""
    dest: "/var/log/php-fpm/{{ server_hostname }}.error.log"
    force: no
    owner: www-data
    group: www-data
    mode: 0644

