---
- hosts: all
  become: true
  tasks:

  - name: update repository index (Ubuntu)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package (Ubuntu)
    apt:
      name: apache2
    when: ansible_distribution == "Ubuntu"

  - name: add php support for apache2 (Ubuntu)
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Ubuntu"

# install apache on CentOS

  - name: update repository index (CentOS)
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install httpd package (CentOS)
    yum:
      name: httpd
    when: ansible_distribution == "CentOS"

  - name: add php support for httpd (CentOS)
    yum:
      name: php
    when: ansible_distribution == "CentOS"
