---
# update packages

- hosts: all
  become: true
  pre_tasks:

  - name: update (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: app
  become: true
  tasks:

# install apache and php on Ubuntu 

  - name: install apache and php package (Ubuntu)
    apt:
      name:
        - apache2
        - libapache2-mod-php       
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# install apache and php on Centos 

  - name: install httpd package (CentOS)
    yum:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: db
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    yum:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
